Repository Kharouk/CameronCam, pull requests merged in 2019-03, with the labels that each got.

#21 Saving Feature Updated to have Description and Image Upload!
  package.json
  public/favicon.gif
  public/favicon.ico
  src/App.js
  src/components/Description.js
  src/components/Header.js
  src/components/ImageUpload.js
  src/components/MapComponent.js
  src/components/__mocks__/FirebaseStorage.js
  src/components/styles/header.css
  src/components/styles/images/bear.gif
  src/components/styles/images/bold.gif
  src/components/styles/images/logo.jpg
  src/components/styles/images/logo2.png
  src/components/styles/images/logo_CC.png
  src/components/styles/images/paper_bag.gif
  src/components/styles/images/patriot.gif
  src/components/styles/images/spiritted.gif
  src/components/styles/images/wig.gif
  src/cors.json
  yarn.lock
Labels: enhancement

#22 User Authentication!
  src/App.js
  src/components/Login.js
  src/components/MapComponent.js
Labels: enhancement

#23 Resize logo header
  package-lock.json
  src/components/styles/header.css
Labels: enhancement

#30 About Section w/ Navigation
  src/App.css
  src/App.js
  src/components/About.js
  src/components/Header.js
  src/components/Login.js
  src/components/MapComponent.js
  src/components/Navigation.js
  src/components/styles/about.css
  src/components/styles/header.css
  src/components/styles/images/pin_head_2x.gif
  src/components/styles/navigation.css
Labels: enhancement, good first issue

#32 User authentication -- Login Component Styled
  src/App.css
  src/App.js
  src/components/Login.js
  src/components/MapComponent.js
  src/components/styles/login.css
Labels: bug, enhancement

#33 Third party authentication
  package.json
  src/App.js
  src/components/Login.js
  src/components/styles/login.css
  yarn.lock
Labels: enhancement

#43 Big PR: Mobile-Friendly, Design Touchups, etc.
  public/index.html
  src/App.css
  src/App.js
  src/components/About.js
  src/components/Description.js
  src/components/Header.js
  src/components/Login.js
  src/components/MapComponent.js
  src/components/styles/about.css
  src/components/styles/header.css
  src/components/styles/images/all_together.gif
  src/components/styles/images/bear.gif
  src/components/styles/images/bold.gif
  src/components/styles/images/paper_bag.gif
  src/components/styles/images/patriot.gif
  src/components/styles/images/spiritted.gif
  src/components/styles/images/toamto.gif
  src/components/styles/images/wig.gif
  src/components/styles/login.css
Labels: enhancement

#44 Contentful For the Back End
  package.json
  src/App.css
  src/App.js
  src/components/About.js
  src/components/Description.js
  src/components/styles/about.css
  yarn.lock
Labels: enhancement

#45 Social media links
  package.json
  src/components/About.js
  src/components/MapComponent.js
  src/components/styles/about.css
  src/components/styles/login.css
  yarn.lock
Labels: enhancement

#50 Loader and flash messages
  package.json
  src/App.css
  src/App.js
  src/components/About.js
  src/components/Button.js
  src/components/Login.js
  src/components/MapComponent.js
  src/components/styles/about.css
  src/components/styles/login.css
  yarn.lock
Labels: enhancement
